### ISSUE TITLE
Is the Warp Consistency Loss be suitable for small motion dataset?

### ISSUE THREAD

**Issue by chenxingxin-star** [PruneTruong/DenseMatching#15]
Hi, Thanks for this wonderful project!
        I want to train an optical flow network on my own dataset, but the view point changes in my dataset is small , Can the WarpC loss get a good result in such dataset?  I found the dataset used in this project have a large view point changes.

**Comment by PruneTruong** [comment]
Hi, sure you can define yourself the strength of the transformation. The only limitation is, if the warp is all 0, then the W-bipath constraint simplifies to the forward-backward consistency constraint, which has a degenerate zero flow solution. 

To sample transformations with small magnitudes, i would recommend sampling the parameters from a gaussian rather than uniformly. You can choose the magnitude of the parameters yourself.
